### ISSUE TITLE
Select a better default account

### ISSUE THREAD

**Issue by markweitzel** [newrelic/nr1-graphiql-notebook#2]
When you first enter the NRQL notebook and select account, a random number come us. This is confusing. Add an account picker and/or default to the first account of the user. (Or maybe the account associated with the API key??)

Below is what I see, even though I'm on account 1. 
{
  actor {
    user {
      email
      name
    }
    account(id: 10)
  }
}

**Comment by tangollama** [comment]
@mattbaker IMO, if we don't have a strong direction on how to address this, we should close it. I'm inclined to do just that. Any objections?

**Comment by mattbaker** [comment]
+1
