### ISSUE TITLE
Need support for complete graphiql

### ISSUE THREAD

**Issue by bl25322** [newrelic/nr1-graphiql-notebook#25]
If my primary account that GraphiQL Notebook is associated with has feature flags for features like EventsToMetrics, these should be supported in the UI.  If someone makes a call where feature flag is not supported, it should error.

If run a call like...
{
  
  actor {
    account(id: xxxxx) {
      eventsToMetrics {
        allRules {
          rules {
            accountId
            description
            enabled
            id
            name
            nrql
          }
        }
      }
    }
  }
}

If I pointed this query to an account that supports this, it just hangs.

**Comment by danielgolden** [comment]
I don't think we can reproduce this anymore :/
