### ISSUE TITLE
'Add New Query' throws error

### ISSUE THREAD

**Issue by ryanv94** [newrelic/nr1-graphiql-notebook#28]
[NOTE]:  Hitting the `Add New Query` button throws console errors & returns the `Opps! Something went wrong` error message. 

## Description

[NOTE]: Hitting the `Add New Query` button throws console errors & returns the `Opps! Something went wrong` error message.

## Steps to Reproduce

[NOTE]: Locally serving `GraphiQl Notebook` Nerdpack; try to `Add New Query`, watch error appear in console and in UI. 

## Relevant Logs / Console output.

<img width="1621" alt="Screenshot 2020-01-06 at 13 48 55" src="https://user-images.githubusercontent.com/37779995/71821918-5d2c6780-308b-11ea-8c33-f5234bb1cc82.png">

[NOTE]: `nr1 nerdpack:serve --verbose` did not reveal anything of interest for me. 

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: `@datanerd/nr1/1.10.10 darwin-x64 node-v10.16.3`
* Browser name and version: `Safari 13.0.3 (15608.3.10.1.4)`
* Operating System and version: `MacOS Catalina: 10.15.1 (19B88)`

---

**_This issue originated in the Explorers Hub: https://discuss.newrelic.com/t/graphiql-notebook/90812_**

**Comment by gauthama-swiggy** [comment]
Not able to save notebook, also there is a loading icon that is always present.  And on clicking add query, something went wrong comes. Please find attached the console output
<img width="1670" alt="screen 1" src="https://user-images.githubusercontent.com/54509907/71822292-887a7b00-30ba-11ea-8287-708ffc4bcd77.png">

**Comment by devfreddy** [comment]
@ryanv94 Thanks for porting the issue over.

@gauthama-swiggy We've found the issue, it's not specific to this Nerdpack. We're discussing internally the best approach to resolve it. Additionally, I'm going to improve a little of the error handling in this Nerdpack so its more clear where its failing at.

**Comment by devfreddy** [comment]
@ryanv94 @gauthama-swiggy The underlying api issue has been resolved, thanks to @mattbaker @binaryseed . I've also added a bit of error handling specifically around the schema query in https://github.com/newrelic/nr1-graphiql-notebook/pull/29 .

🚀
