### ISSUE TITLE
Fails to return Graphql results

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/nr1-graphiql-notebook#58]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
Some queries throw a JS error and never return results. While I use the example notebook for the example below, I also observed this behavior with a new notebook.

First example fails:
<img width="1401" alt="Screen Shot 2021-04-01 at 10 59 37 AM" src="https://user-images.githubusercontent.com/70179303/113335286-9462e600-92d9-11eb-88b4-b326d95aeea2.png">
With a JS error
<img width="1781" alt="Screen Shot 2021-04-01 at 11 00 57 AM" src="https://user-images.githubusercontent.com/70179303/113335291-96c54000-92d9-11eb-8b8f-54039302fd90.png">

Second example works fine:
<img width="1438" alt="Screen Shot 2021-04-01 at 10 59 58 AM" src="https://user-images.githubusercontent.com/70179303/113335288-962ca980-92d9-11eb-93d7-335f17c67497.png">

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )
1. Open the Graphql Notebook
2. Run the first example
3. Notice that it never returns results

## Expected Behaviour

[NOTE]: # ( Tell us what you expected to happen. )
The Graphql results are displayed.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* NR1 CLI version used: @datanerd/nr1/1.32.0 darwin-x64 node-v10.16.3
* Browser name and version: Chrome 89.0.4389.90 (Official Build) (x86_64)
* Operating System and version: MacOS Big Sur 11.2.3

**Comment by aswanson-nr** [comment]
After further investigation, this appears to have something to do with the `NerdGraphQuery` module from the `nr1` package.
When querying for something like 
```gql
{
    actor {
        user {
           name
        }
   }
}
```
The correct values are returned, but they include an extra `id` field for the user, which breaks the response parsing of this application.

**Comment by rudouglas** [comment]
I resolved this issue by first checking if there was a `contextNode` object, and then checking if it had `contextNode.context`, this has resolved the issue
