### ISSUE TITLE
Graphiql notebook won't run locally

### ISSUE THREAD

**Issue by jpvajda** [newrelic/nr1-graphiql-notebook#62]
I was attempting to run the graphql notebook app locally to look at the console errors, but I'm getting a ton of errors from running NPM start.  Not sure what that issue is, I've tried all my tricks.. 🪄 

### Steps to reproduce

- Pull down the most current code
- run npm install
- run npm start
- view the terminal output

### Expected

User can run this app locally

### Errors

There were probably a 100 of these, this is just a small sample.
```

ERROR in ./node_modules/graphql/index.mjs 25:0-49
    Can't reexport the named export 'version' from non EcmaScript module (only default export is available)
     @ ./nerdlets/notebook-nerdlet/index.js
    
    ERROR in ./node_modules/graphql/index.mjs 25:0-49
    Can't reexport the named export 'versionInfo' from non EcmaScript module (only default export is available)
     @ ./nerdlets/notebook-nerdlet/index.js
    
    ERROR in ./node_modules/graphql/index.mjs 42:0-48:205
    Can't reexport the named export 'visit' from non EcmaScript module (only default export is available)
     @ ./nerdlets/notebook-nerdlet/index.js
    
    ERROR in ./node_modules/graphql/index.mjs 42:0-48:205
    Can't reexport the named export 'visitInParallel' from non EcmaScript module (only default export is available)
     @ ./nerdlets/notebook-nerdlet/index.js
    
    ERROR in ./node_modules/graphql/index.mjs 42:0-48:205
    Can't reexport the named export 'visitWithTypeInfo' from non EcmaScript module (only default export is available)
     @ ./nerdlets/notebook-nerdlet/index.js

```

**Comment by rudouglas** [comment]
I think the CLI has deprecated the use of `.extended-webpackrc.js` which is causing the fix for this to not work, checking with the team who owns the CLI

**Comment by jpvajda** [comment]
Here is the app usage for Grapiql notebook

<img width="1274" alt="Screen Shot 2021-11-10 at 3 23 32 PM" src="https://user-images.githubusercontent.com/1395158/141203607-a4b64cb8-6a4e-41b5-b053-194cbf2ae013.png">

**Comment by jpvajda** [comment]
@rudouglas what would it take to fix this app? @zstix isn't the only user of it, 🤣 but if the effort to resolve this outweighs the minimal usage I am seeing we could look to deprecate this app from the catalog.

**Comment by rudouglas** [comment]
@jpvajda I think we've found a bug in the CLI which is causing this issue, working with the team to resolve it. Beyond that the app is working unless we find some other issue when this one is resolved. I wonder if it would be worth reaching out to the users have a used it in the last few months for feedback on whether they find it useful, how regularly they use it and what use-cases they have. Even add a banner in the app with a link to a Google form to collect feedback. Then we could make a decision based on the data. We could do this for all the apps too I think it would be a better way to gauge usage.

**Comment by jpvajda** [comment]
@rudouglas interesting idea.. I think for now i'd say:

1. lets see if we can get that NR1 CLI issue resolved with the core team.
2. let's keep this app in the catalog, as it's actually pretty useful to learn Graphql 
3. let's explore how we can validate usefulness of 3rd party apps with some sort of survey or feedback mechanism. I'll make a ticket for that. I'm working on some OSS / 3rd party app stuff with @polfliet 🥳

**Comment by jpvajda** [comment]
@rudouglas what is JIRA issue that relates to the CLI bug, can you just put that ID number in the ticket for reference?

**Comment by jpvajda** [comment]
https://github.com/newrelic/nr1-catalog/issues/410

**Comment by jpvajda** [comment]
@rudouglas well.. this is occuring on staging

`426 - Nerdlet graphql-api-explorer.graphiql-nerdlet was built with an unsupported CLI` 

so not sure if this is even working let me check prod....

**Comment by jpvajda** [comment]
it looks like the production version of graphql loads correctly...



<img width="1784" alt="Screen Shot 2021-11-11 at 3 25 54 PM" src="https://user-images.githubusercontent.com/1395158/141377896-674129e9-b0f6-41b2-8309-7f67978c15ac.png">

**Comment by rudouglas** [comment]
Hmm ye i think as long as it's currently working in Production it's less of an issue, i'll follow up with the team and get a Jira number for the work.

Delighted to hear y'all are working on 3rd-party/OSS stuff that's music to my ears 🎶👂

**Comment by rudouglas** [comment]
A new version of the CLI v2.42.2 was released which resolves these errors
