### ISSUE TITLE
Modal related JS error?

### ISSUE THREAD

**Issue by mattbaker** [newrelic/nr1-graphiql-notebook#9]
With the introduction of the modal component we started seeing this in the logs:

> `wanda--wanda-ec-ui--third-party-sdk-release-576.js:153 Uncaught (in promise) TypeError: Cannot convert undefined or null to object`

It's very possible we're simply using the modal component incorrectly. I am not a React developer.

**Comment by devfreddy** [comment]
Did some digging on this. It's morphed a little bit since September into:

```
Uncaught (in promise) TypeError: Cannot read property '__factory' of undefined
    at wanda--wanda-ec-ui--third-party-sdk-release-819.js:172
value @ wanda--wanda-ec-ui--app-release-819.js:210
value @ wanda--wanda-ec-ui--app-release-819.js:210
value @ wanda--wanda-ec-ui--app-release-819.js:210
nrWrapper @ nr-loader-spa-current.min.js:1
```

Seems to be related to an internal refactor of some pieces of the nr1 sdk. It's a known issue. In the meantime - it doesn't affect functionality, I vote we close.

@tangollama feel free to reopen if you disagree.
